# Generated by Django 4.1.1 on 2022-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=200)),
                ('Item_desc', models.CharField(max_length=200)),
                ('Item_price', models.IntegerField()),
            ],
        ),
    ]
